#!/bin/sh

BACKUP_FOLDER=$1

if [ "$BACKUP_FOLDER" = "" ];
then
    echo "Backup folder is not provided."
    exit
fi

if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo:"
    echo "sudo $0 $*"
    exit 1
fi

BACKUP_FOLDER="$BACKUP_FOLDER/"

if [ ! -d "$BACKUP_FOLDER/dev" ]
then
    echo "$BACKUP_FOLDER/dev DOES NOT exists."
    exit 1
fi

DST="/home/max/123"

rsync -aAXHv --delete --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found","$BACKUP_FOLDER","/home/*"} $BACKUP_FOLDER $DST
